#!/bin/sh
set -e
echo 'delay-start: Waiting 10 seconds'
sleep 10
echo 'delay-start: Installing ssh-keys'
cp -R /opt/post-run/.ssh/ /var/go/.ssh/
chown -R go:go /var/go/.ssh
chmod 700 /var/go/.ssh
chmod 400 /var/go/.ssh/*
ls -alR /var/go
echo 'delay-start: Done'
